name: XMusic
options:
  bundleIdPrefix: xmusic
  deploymentTarget:
    iOS: "15.0"

targets:
  XMusic:
    type: application
    platform: iOS
    sources:
      - path: Sources
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        CODE_SIGN_ENTITLEMENTS: XMusic.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: xmusic.XMusic
        PRODUCT_NAME: XMusic
        CODE_SIGNING_ALLOWED: "NO"
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_VERSION: "5.9"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_USER_SCRIPT_SANDBOXING: "NO"
        APPLICATION_SCENE_MANIFEST_GENERATION: "NO"
